### ISSUE TITLE
Show Quiz Questions and Edit Score display offscreen in Firefox

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#234]
![image](https://cloud.githubusercontent.com/assets/16817089/19651160/aa221566-9a03-11e6-8594-7880dbaa78f2.png)

**Comment by minaorangina** [comment]
Changes required:
```html
<div class="modal-background modal-content-outer">
  <div class="modal-content-middle">
    <div class="modal-content-inner section container>
      ... ...
    </div>
  </div>
</div>
```
```css
.modal-content-inner {
  overflow-y: auto;
  -ms-overflow-style: -ms-autohiding-scrollbar;
}
```
