### ISSUE TITLE
Problems configuring postgres for CircleCI

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#33]
### Solution
CircleCI has some popular databases set up by default.
In `circle.yml`, wrote a script that would create a database with username `ubuntu` and database name `circle_test` (the CircleCI defaults)

```yml
database:
  override:
    - psql -U ubuntu circle_test < `path/to/schema`
```

[CircleCI: setting up your test databases](https://circleci.com/docs/manually/#databases)
