### ISSUE TITLE
Refactor BEM

### ISSUE THREAD

**Issue by harrygfox** [cul-2016/quiz#381]
Lots of scss partials need their BEM improving / can be made more DRY.

By way of example the current state of buttons.scss features: 
```css
    &--large {
        font-size: 1.5rem;
        line-height: 2;
        padding: 0.5rem 1rem;
    }

    &__primary {
        background-color: $gold;
        color: $black;
        box-shadow: inset 0 -3px 0 0 $dark-gold;

        &--large {
            font-size: 1.5rem;
            line-height: 2;
            padding: 0.5rem 1rem;
        }
    }

    &__secondary {
        background-color: $blue;
        color: white;
        box-shadow: inset 0 -3px 0 0 $dark-blue;

        &--large {
            font-size: 1.5rem;
            line-height: 2;
            padding: 0.5rem 1rem;
        }
    }

    &__tertiary {
        background-color: #EB415C;
        color: $white;
        box-shadow: inset 0 -3px 0 0 #C10F2B;

        &--large {
            font-size: 1.5rem;
            line-height: 2;
            padding: 0.5rem 1rem;
        }
    }
```
Here 3 lines:
```css
font-size: 1.5rem;
line-height: 2;
padding: 0.5rem 1rem;
```
Are **repeated 4 times**. What's more :

## modifiers are chained _on the markup_ NOT in CSS

To make a large primary button you just add both modifier classes e.g.:
```html
<input value="submit" type="submit" class="button button--primary button--large">
```
